#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  repos=$(find $REPOS_DIR -mindepth 1 -maxdepth 1 -type d)
  selected=$(for repo in $repos; do
    if git -C "$repo" rev-parse --git-dir > /dev/null 2>&1; then
      worktrees=$(git -C "$repo" worktree list | awk '{print $1}')
      if [[ $(wc -l <<< "$worktrees") -gt 1 ]]; then
        grep -v "^$repo\$" <<< "$worktrees"
      else
        echo "$repo"
      fi
    else
      echo "$repo"
    fi
  done | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# tmux is not running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  tmux a -t $selected_name
  exit 0
fi

# auto connect to default
if tmux has-session -t=$selected_name 2> /dev/null; then
  tmux a -t $selected_name
fi

# tmux is running, but no session is running
if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
  tmux switch-client -t $selected_name
fi
